### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Kabron287** [Protocentral/protocentral_openview#1]
Windows 10 x64
Port selection does not allow to select anything except COM1 and it is allways busy.
Shame!
![BUG](https://user-images.githubusercontent.com/2493191/86023833-def6bf80-ba34-11ea-9c44-57e5bb53e339.jpg)

**Comment by MohammedHM** [comment]
Dear Kabron,

I would like to assist you to resolve your issue. Could you please provide us the following details,
1. Which breakout board your using for displaying in the GUI?
2. Connection image of the breakout and Arduino UNO.

Unplug and Plug the Arduino UNO.

Regards,
Mohammed Ibrahim H

**Comment by Kabron287** [comment]
Hello, Mohammed!

I found out the trick. It's controlled by up/dow keys or mouse wheel.
But it is not obvious, especially after pulse-oximeter application.
IMHO it must be stated out somewhere.
Sorry for sharp claim.
