### ISSUE TITLE
No Tiny GSR Board 

### ISSUE THREAD

**Issue by samreg** [Protocentral/protocentral_openview#7]
Hello, I bought you a tiny GSR Board. I am installing openview as said in your tuto, but when i launch Openview, Tiny GSR board does not appear in the board list.

I use the zip source code install
Best regards

**Comment by awhitchurch** [comment]
Hello @samreg  We have added support, but the release files have not been created. I will test and create a release soon. Thank you for reporting.

**Comment by awhitchurch** [comment]
@samreg , new version v1.2.0 (https://github.com/Protocentral/protocentral_openview/releases/tag/v1.2.0) has been released which includes this support for tinyGSR

**Comment by samreg** [comment]
Thanks !
